name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: maven:3.9.6-eclipse-temurin-17

    steps:
      - uses: actions/checkout@v4
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Super-linter
        uses: super-linter/super-linter@v8.1.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          #GITHUB_TOKEN:
          #RUN_LOCAL: true
          DEFAULT_BRANCH: main
          VALIDATE_JAVA: true
          FILTER_REGEX_INCLUDE: ^src/
          SAVE_SUPER_LINTER_SUMMARY: true
          SAVE_SUPER_LINTER_OUTPUT: true
          
      - name: Run tests
        run: mvn test